name: xml2rfc

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install xml2rfc
    - name: Set up Go
      uses: actions/setup-go@v5
    - name: download mmark
      uses: robinraju/release-downloader@v1
      with:
        repository: mmarkdown/mmark
        tag: v2.2.47
        fileName: mmark_2.2.47_linux_amd64.tgz 
    - name: un-tar
      run: |
        tar xzvf mmark_2.2.47_linux_amd64.tgz
    - name: mmark
      run: |
        ./mmark < draft-ietf-deleg.md > draft-ietf-deleg.xml && cat draft-ietf-deleg.xml
    - name: run xml2rfc
      run: |
        xml2rfc draft-ietf-deleg.xml && cat draft-ietf-deleg.txt
    - name: Commit updated file
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Action
        author_email: action@github.com
        message: "Regenerate .txt"
        add: draft-ietf-deleg.txt
    - name: Push I-D file
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
